# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Production Build and Deploy

on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ./wingit

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
        
        
    - name: Build with Maven
      run: |
            mvn -B package -P prod --file pom.xml -Dmaven.test.skip
            mkdir artifacts && cp target/*.jar artifacts
            cd artifacts && ls
    - name: Create Timestamp for Version Info
      id: time
      uses: nanzm/get-time-action@v2.0
      with:
        format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: "Artifact-${{steps.time.outputs.time}}"
        path: ./wingit/artifacts
        retention-days: 8

    - name: Beanstalk Deploy for JAR
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: wingit
        environment_name: wingit-env-prod
        version_label: wingit-${{steps.time.outputs.time}}
        region: ap-southeast-1
        deployment_package: ./wingit/artifacts/wingit-prod.jar


    
